name: Deploy Prefect flow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Prefect deployments'
        required: false
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set date for image tag
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Install Prefect
        run: |
          python -m pip install --upgrade pip
          pip install prefect  
      - name: Prefect Deploy
        env:
          NOW: ${{ env.NOW }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_AUTH_STRING: ${{ secrets.PREFECT_API_AUTH_STRING }}
        run: |
          prefect deploy --all --prefect-file automation/prefect/prefect-git-clone.yaml build-image.tag=$NOW
